### PR TITLE
Sync multiple leads

### PR DESCRIPTION
**Pull request by markadrianagbuya**
I needed this as well. It uses the same soap request as syncing a single custom object except the request body is formatted a little differently for multiple custom objects.

### CODE REVIEW

**Comment by davidsantoso** [comment]
LGTM. Thanks again! Also, mind changing the version number to 2.3.1? Once that happens I'll merge in and push it to RubyGems.

**Comment by markadrianagbuya** [comment]
Actually, there are a few more things that I realised after using this code that would make things more convenient, like representing each lead response with an object instead of just a raw hash. I'll push my changes soon and change the version number.

**Comment by davidsantoso** [comment]
Sounds good. Just ping me when you're ready.

**Comment by markadrianagbuya** [comment]
Ok changes are pushed.

**Comment by davidsantoso** [comment]
Merged and pushed to RubyGems. Thanks!

**Comment by markadrianagbuya** [comment]
Awesome. Thanks!

**Pull request merged**
