### PR TITLE
Added API for syncing/getting Marketo custom objects

### PR DESCRIPTION
**Pull request by markadrianagbuya**
Marketo custom objects allow you to have a one-to-many relationship between your leads and the custom objects. For example, a marketo_lead has many purchases or products. Then you can make campaigns centered on the products and send emails per product instead of per lead.

Here are the API docs for the custom objects: http://developers.marketo.com/documentation/soap/custom-object-operations/

### CODE REVIEW

**Comment by davidsantoso** [comment]
Thanks for submitting this PR! Custom objects was definitely something nice to be integrated. I'll be taking a look at it tomorrow and get back to you with any questions or concerns.

**Comment by davidsantoso** [comment]
Everything LGTM. Merging in. Thanks!

**Comment by davidsantoso** [comment]
Tagged and pushed the changes to RubyGems. Thanks for contributing!

**Comment by markadrianagbuya** [comment]
Awesome! Thanks

**Pull request merged**
